config/routes.rb
Rails.application.routes.draw do

  mount Rich::Engine => '/rich', :as => 'rich'
  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    match '/signin', to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'

    resources :manager

    root 'dashboard#index'

    resources :pages do
      collection do
        post :rebuild
        get '/all' => 'pages#all'
        get '/find/:id' => 'pages#find'
      end
    end

    resources :products
    get '/products/find/:id' => 'products#find'
    post '/products/:product_id/property/:property_id/value/:value_id' => 'products#set_property_value'
    post '/products/:product_id/brand/:brand_id' => 'products#set_brand'
    post '/products/:product_id/category/:category_id' => 'products#set_category'

    get '/products/:product_id/sub_product/new' => 'products#sub_product_new'
    put '/sub_product/:sub_product_id' => 'products#sub_product_update'
    get '/products/:product_id/sub_product/:sub_product_id/destroy' => 'products#sub_product_destroy'
    
    resources :categories do
      collection do
        post :rebuild
      end
    end

    resources :brands do
      collection do
        post :rebuild
      end
    end

    resources :news
    
    resources :properties do
      post :values
      delete '/values/:id' => 'properties#delete_value'
    end

    resources :feedbacks

    get '/categories/find/:id' => 'categories#find'
    get '/brands/find/:id' => 'brands#find'

    get '/product/photos/:product_id' => 'photos#find'
    post '/product/photos/upload' => 'photos#upload'
    
    get '/sub_product/photos/:sub_product_id' => 'photos#find_sub_product'
    post '/sub_product/photos/upload' => 'photos#upload_sub_product'
    
    get '/category/photos/:category_id' => 'photos#find_category'
    post '/category/photos/upload' => 'photos#upload_category'

    get '/brand/photos/:brand_id' => 'photos#find_brand'
    post '/brand/photos/upload' => 'photos#upload_brand'

    get '/gallery/photos/:gallery_id' => 'photos#find_gallery'
    post '/gallery/photos/upload' => 'photos#upload_gallery'

    delete '/photos/:id' => 'photos#destroy'
    put '/photos/edit/:id' => 'photos#update'

    resources :galleries do

    end

  end

  post '/feedback/create' => 'feedbacks#create'

  root 'pages#index'
  get '/root' => 'pages#index'

  get '/pages/carousel' => 'pages#carousel'

  get '/product/filters/' => 'products#filters'

  get '/catalog/:category_id/product/:product_id' => 'pages#product'
  get '/catalog/*section/:category_id/product/:product_id' => 'pages#product'
  get '/catalog/*section/*section/:category_id/product/:product_id' => 'pages#product'

  get '/catalog' => 'pages#catalog'
  
  
  get '/bathroom-tile', to: redirect('/catalog/bathroom-tile')
  get '/bathroom-tile/:name', to: redirect('/catalog/bathroom-tile')
  get '/floors-tiles', to: redirect('/catalog/floors-tiles')
  get '/floors-tiles/:name', to: redirect('/catalog/floors-tiles')
  get '/mosaic', to: redirect('/catalog/mosaic')
  get '/mosaic/:name', to: redirect('/catalog/mosaic')
  get '/keramogranit', to: redirect('/catalog/keramogranit')
  get '/keramogranit/:name', to: redirect('/catalog/keramogranit')
  get '/decorative-items', to: redirect('/catalog/decorative-items')
  get '/decorative-items/:name', to: redirect('/catalog/decorative-items')
  get '/tiles-for-kitchen.html', to: redirect('/catalog/tiles-for-kitchen')
  get '/brand', to: redirect('/brands')
  
  
  get '/catalog/:id' => 'pages#category'
  get '/catalog/*section/:id' => 'pages#category'
  get '/catalog/*section/*section/:id' => 'pages#category'

  get '/brands' => 'pages#brands', :as => 'brands'
  get '/brands/:id' => 'pages#brand'

  get '/news' => 'news#index'
  get '/news/:id' => 'news#show', :as => 'news_show'
  
  get ':id' => 'pages#show'

end

app/models/admin/brand.rb
class Admin::Brand < ActiveRecord::Base
  has_and_belongs_to_many :products
  has_and_belongs_to_many :photos


  validates :name, length: {minimum: 1}
  validates :path, length: {minimum: 1}, uniqueness: true


  acts_as_nested_set
  include TheSortableTree::Scopes


  def full_path
    @parents = self.self_and_ancestors.select(:path)
    @path = @parents.map do |p|
      "/" + p.path
    end
    @path.join()
  end


end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_and_belongs_to_many :products
  has_and_belongs_to_many :photos

  acts_as_nested_set
  include TheSortableTree::Scopes

  def to_param
    "#{path}"
  end

  def front_full_path
    @parents = self.self_and_ancestors.select(:path)
    @path = ["/brands"]
    @path += @parents.map do |p|
      "/" + p.path
    end
    @path.join()
  end
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < Admin::AdminController
  before_action :signed_in_manager
  before_action :set_item, only: [:show, :find, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  include TheSortableTreeController::Rebuild


  def index
    @brands = Admin::Brand.all.order('lft ASC')
    @clear_nill_brand = Admin::Brand.find_by_name("название")
    if @clear_nill_brand
      @clear_nill_brand.destroy
    end
  end

  def show
  end

  def new
    @brand = Admin::Brand.new(
        :name => "название"
    )
    if @brand.save validate: false
      redirect_to edit_admin_brand_url(@brand)
    else
      render :json => {error: @brand.errors}
    end
    # @brands = Admin::Brand.all
  end

  def edit
    @brands = Admin::Brand.all
  end

  def find
    @brand_translation = Admin::Brand.find(params[:id])
    render :json => @brand_translation
  end

  def update
    if @brand.update(brand_params)
      render :json => {success: @brand}
    else
      render :json => {error: @brand.errors}
    end
  end

  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to admin_brands_url, notice: 'Бренд успешно удален!' }
      format.json { head :no_content }
    end
  end

  private
  def set_item
    @brand = Admin::Brand.find(params[:id])
  end

  def brand_params
    params.require(:brand).permit(:sortable, :parent_id, :path, :name, :body)
  end
end

app/views/admin/brands/_form.slim
.panel.panel-success
  .panel-heading
    h3.panel-title Информация о бренде

  .panel-body
    .alert.alert-danger ng-if="errors"
      h4.text-center При сохранении возникли следующие ошибки:
      br
      dl.dl-horizontal ng-if="errors.name" 
        dt Название: 
        dd ng-bind="errors.name[0]"
      dl.dl-horizontal ng-if="errors.path" 
        dt Путь: 
        dd ng-bind="errors.path[0]"
    .row
      .col-md-6
        .form-group
          label for="name" Название
          input.form-control#name name="name" type="text" ng-model="obj.name" ng-change="setPath(obj.name)" 

      .col-md-6
        .form-group
          label for="path" Путь(url, например - kamod, только латиницей)
          input.form-control#path type="text" ng-model="obj.path"
    .row
      .col-sm-12
        photos-uploaded resource-name="brand" resource-id="#{@brand.id}"
        uploader-component upload-url="/admin/brand/photos/upload" resource-name="brand_id" resource-id="#{@brand.id}"

app/views/admin/brands/edit.slim
form ng-controller="BrandsFormCtrl"

  .page-header
    h2 Добавить/редактировать бренд
    .page-header-actions
      button.btn.btn-success type="submit" ng-click="update('#{@brand.id}')" ng-init="findBrand('#{@brand.id}')"
        i.fa.fa-floppy-o
        | Сохранить
      =link_to "Отменить", admin_brands_path, :class => "btn btn-default"

  =render 'admin/brands/form'

app/views/admin/brands/index.slim
.page-header
  h2 Бренды
  .page-header-actions
    = link_to new_admin_brand_path, class: 'btn btn-success' do
      i class="fa fa-plus"
      ' Добавить бренд

.content.page
  ol.sortable_tree data-max_levels="5" data-rebuild_url="#{rebuild_admin_brands_url}"
    = sortable_tree @brands

app/views/admin/brands/new.slim
form ng-controller="BrandsFormCtrl"

  .page-header
    h2 Добавить бренд
    .page-header-actions
      button.btn.btn-success type="submit" ng-click="update('#{@brand.id}')" ng-init="findBrand('#{@brand.id}')"
        i.fa.fa-floppy-o
        | Сохранить
      =link_to "Отменить", admin_brands_path, :class => "btn btn-default"

  =render 'admin/brands/form'

app/views/admin/brands/show.slim
h2.page-header=@brand.name
div=@brand.path