config/routes.rb
Rails.application.routes.draw do

  mount Rich::Engine => '/rich', :as => 'rich'
  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    match '/signin', to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'

    resources :manager

    root 'dashboard#index'

    resources :pages do
      collection do
        post :rebuild
        get '/all' => 'pages#all'
        get '/find/:id' => 'pages#find'
      end
    end

    resources :products
    get '/products/find/:id' => 'products#find'
    post '/products/:product_id/property/:property_id/value/:value_id' => 'products#set_property_value'
    post '/products/:product_id/brand/:brand_id' => 'products#set_brand'
    post '/products/:product_id/category/:category_id' => 'products#set_category'

    get '/products/:product_id/sub_product/new' => 'products#sub_product_new'
    put '/sub_product/:sub_product_id' => 'products#sub_product_update'
    get '/products/:product_id/sub_product/:sub_product_id/destroy' => 'products#sub_product_destroy'
    
    resources :categories do
      collection do
        post :rebuild
      end
    end

    resources :brands do
      collection do
        post :rebuild
      end
    end

    resources :news
    
    resources :properties do
      post :values
      delete '/values/:id' => 'properties#delete_value'
    end

    resources :feedbacks

    get '/categories/find/:id' => 'categories#find'
    get '/brands/find/:id' => 'brands#find'

    get '/product/photos/:product_id' => 'photos#find'
    post '/product/photos/upload' => 'photos#upload'
    
    get '/sub_product/photos/:sub_product_id' => 'photos#find_sub_product'
    post '/sub_product/photos/upload' => 'photos#upload_sub_product'
    
    get '/category/photos/:category_id' => 'photos#find_category'
    post '/category/photos/upload' => 'photos#upload_category'

    get '/brand/photos/:brand_id' => 'photos#find_brand'
    post '/brand/photos/upload' => 'photos#upload_brand'

    get '/gallery/photos/:gallery_id' => 'photos#find_gallery'
    post '/gallery/photos/upload' => 'photos#upload_gallery'

    delete '/photos/:id' => 'photos#destroy'
    put '/photos/edit/:id' => 'photos#update'

    resources :galleries do

    end

  end

  post '/feedback/create' => 'feedbacks#create'

  root 'pages#index'
  get '/root' => 'pages#index'

  get '/pages/carousel' => 'pages#carousel'

  get '/product/filters/' => 'products#filters'

  get '/catalog/:category_id/product/:product_id' => 'pages#product'
  get '/catalog/*section/:category_id/product/:product_id' => 'pages#product'
  get '/catalog/*section/*section/:category_id/product/:product_id' => 'pages#product'

  get '/catalog' => 'pages#catalog'
  
  
  get '/bathroom-tile', to: redirect('/catalog/bathroom-tile')
  get '/bathroom-tile/:name', to: redirect('/catalog/bathroom-tile')
  get '/floors-tiles', to: redirect('/catalog/floors-tiles')
  get '/floors-tiles/:name', to: redirect('/catalog/floors-tiles')
  get '/mosaic', to: redirect('/catalog/mosaic')
  get '/mosaic/:name', to: redirect('/catalog/mosaic')
  get '/keramogranit', to: redirect('/catalog/keramogranit')
  get '/keramogranit/:name', to: redirect('/catalog/keramogranit')
  get '/decorative-items', to: redirect('/catalog/decorative-items')
  get '/decorative-items/:name', to: redirect('/catalog/decorative-items')
  get '/tiles-for-kitchen.html', to: redirect('/catalog/tiles-for-kitchen')
  get '/brand', to: redirect('/brands')
  
  
  get '/catalog/:id' => 'pages#category'
  get '/catalog/*section/:id' => 'pages#category'
  get '/catalog/*section/*section/:id' => 'pages#category'

  get '/brands' => 'pages#brands', :as => 'brands'
  get '/brands/:id' => 'pages#brand'

  get '/news' => 'news#index'
  get '/news/:id' => 'news#show', :as => 'news_show'
  
  get ':id' => 'pages#show'

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :photos
  has_and_belongs_to_many :properties
  has_and_belongs_to_many :values
  has_and_belongs_to_many :brands
  has_many :sub_products

  paginates_per 12


  # scope :filter, -> (value_id){ joins(:values).group("id"){ where(id: value_id)} }

  scope :filter, -> (value_id) { joins(:values).where('values.id = ?', value_id) }

  validates :price, :numericality => true


  # VALID_NAME_REGEX = /"Название продукта"/i
  validates :name, presence: true
  # validates :name, format: {with: VALID_NAME_REGEX}


  def prop_val
    @product_properties = []
    Property.all.each do |property|
      property_values = []
      property.values.each do |value|
        unless self.values.exists?(value)
          property_value = {id: value.id, value: value.value, checked: 0}
          property_values.push property_value
        else
          property_value = {id: value.id, value: value.value, checked: 1}
          property_values.push property_value
        end
      end
      product_property = {id: property.id, name: property.name, values: property_values}
      @product_properties.push product_property
    end
    return @product_properties
  end

  def brand_ser
    @product_brands = []
    Brand.all.each do |brand|
      unless self.brands.exists?(brand)
        brand = {id: brand.id, name: brand.name, checked: 0}
      else
        brand = {id: brand.id, name: brand.name, checked: 1}
      end
      @product_brands.push brand
    end
    return @product_brands
  end

  def category_ser
    @product_categories = []
    Category.all.each do |category|
      unless self.categories.exists?(category)
        category = {id: category.id, name: category.name, checked: 0}
      else
        category = {id: category.id, name: category.name, checked: 1}
      end
      @product_categories.push category
    end
    return @product_categories
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :signed_in_manager, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  before_action :set_product, only: [:show, :find, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token


  def index
    @products = Product.all
    @prod_delete = Product.find_by_name("Название продукта")
    if @prod_delete
      @prod_delete.destroy
    end
  end

  def show
  end

  def new
    @product = Product.new(:price => 0, :name => "Название продукта")
    @sub_prod = SubProduct.new(:name => "Декоративные элементы")
    @product.sub_products << @sub_prod
    if @product.save
      redirect_to edit_admin_product_url(@product)
    else
      render :json => {error: @product.errors}
    end
  end

  def edit
  end

  def find
    @categories = @product.category_ser
    @brands = @product.brand_ser
    @properties_values = @product.prop_val
    render :json => {
        product: @product,
        sub_products: @product.sub_products,
        product_categories: @product.categories,
        product_brands: @product.brands,
        categories: @categories,
        brands: @brands,
        properties: @properties_values
    }
  end


  def create
    @product = Product.new(product_params)
    if @product.save
      render :json => {success: @product}
    else
      render :json => {error: @product.errors}
    end
  end

  def update
    if @product.update(product_params)
      render :json => {success: @product}
    else
      render :json => {error: @product.errors}
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_property
    @product = Product.find(params[:product_id])
    @property = Property.find(params[:property_id])
    @product.properties << @property
    @properties = Property.all - @product.properties
    render :json => {
        properties: @properties,
        product_properties: @product.properties
    }
  end

  def set_property_value
    @product = Product.find(params[:product_id])
    @property = Property.find(params[:property_id])
    @value = Value.find(params[:value_id])
    unless @product.properties.exists?(@property)
      @product.properties << @property
    end
    unless @product.values.exists?(@value)
      @product.values << @value
    else
      @product.values.delete(@value)
      if @product.values.where(property_id: @value.property_id).length == 0
        @product.properties.delete(@property)
      end
    end
    render :json => {
        properties: @product.prop_val
    }
  end

  def set_brand
    @product = Product.find(params[:product_id])
    @brand = Brand.find(params[:brand_id])
    unless @product.brands.exists?(@brand)
      @product.brands << @brand
    else
      @product.brands.delete(@brand)
    end
    render :json => {
        brands: @product.brand_ser
    }
  end

  def set_category
    @product = Product.find(params[:product_id])
    @category = Category.find(params[:category_id])
    unless @product.categories.exists?(@category)
      @product.categories << @category
    else
      @product.categories.delete(@category)
    end
    render :json => {
        brands: @product.category_ser
    }
  end

  def sub_product_new
    @product = Product.find(params[:product_id])
    @sub_product = SubProduct.create()
    @product.sub_products << @sub_product
    render :json => @product.sub_products
  end

  def sub_product_update
    @product = Product.find(params[:product_id])
    @sub_product = SubProduct.find(params[:sub_product_id])
    @sub_product.update(:name => params[:name])
    render :json => @product.sub_products
  end

  def sub_product_destroy
    logger.debug params
    @product = Product.find(params[:product_id])
    @sub_product = SubProduct.find(params[:sub_product_id])
    @sub_product.destroy
    render :json => @product.sub_products
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :body, :price, :sale, :art, :new, :property_id, :value_id, :brand_id, :category_id, :sub_product_id)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def filters
    filters = []
    JSON.parse(params[:filters]).each do |f|
      filters.push f[1]
    end

    @products = Product.filter(filters.join(","))

    def prod_val(products, filters)
      @p = []
      if filters.length > 0
        f = filters.shift
        for product in products
          if product.values.exists?(f)
            @p.push product
          end
        end
        @p = @p.uniq
        prod_val(@p, filters)
      else
        return @p = products
      end
    end

    @products = prod_val(@products, filters)
    
    @res = []
    @products.each do |product|
      prod = {product: nil, values: nil}
      prod[:product] = product
      prod[:values] = product.values
      @res.push prod
    end

    render :json => @res
  end


  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:price, :title, :body, :filters)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_brands.erb
<div class="form-group">
  <label>Бренды</label>
  <div class="checkbox" ng-repeat="brand in brands">
    <label>
      <input type="checkbox"
             ng-model="brand[$index]"
             ng-change="setBrand(obj.product.id, brand.id)"
             ng-checked="brand.checked"
      >
      <span>{{brand.name}}</span>
    </label>
  </div>
</div>

app/views/admin/products/_categories.erb
<div class="form-group">
  <label>Категории</label>

  <div class="checkbox" ng-repeat="category in categories">
    <label>
      <input type="checkbox"
             ng-model="category[$index]"
             ng-change="setCategory(obj.product.id, category.id)"
             ng-checked="category.checked"
      >
      <span>{{category.name}}</span>
    </label>
  </div>
</div>

app/views/admin/products/_form.slim
.panel.panel-success
  .panel-heading.clearfix
    h3.panel-title.pull-left Информация о товаре

  .panel-body
    .alert.alert-danger ng-if="errors"
      ul ng-repeat="error in errors"
        li ng-bind="error"
    .row
      .col-md-6
        .form-group
          label for="name" Название
          input.form-control#name name="name" type="text" ng-model="obj.product.name"
      .col-md-4
        .form-group
          label for="price" Цена(руб.)
          input.form-control#price type="text" ng-model="obj.product.price"
      .col-md-2
        .form-group
          div class="checkbox"
            label 
              input id="new" type="checkbox" ng-model="obj.product.new"
              |Новинка

    div
      label for="body_ru" Описание
      textarea.form-control#body_ru rows="4" ng-model="obj.product.body"


.panel.panel-success
  .panel-heading.clearfix
    h3.panel-title.pull-left Фотографии товара
  .panel-body
    photos-uploaded resource-name="product" resource-id="#{@product.id}"
    uploader-component upload-url="/admin/product/photos/upload" resource-name="product_id" resource-id="#{@product.id}"


.panel.panel-success
  .panel-heading.clearfix
    h3.panel-title.pull-left Категории/Бренды
  .panel-body
    .row
      .col-sm-6
        =render 'admin/products/categories'
      .col-sm-6
        =render 'admin/products/brands'


.panel.panel-success
  .panel-heading.clearfix
    h3.panel-title.pull-left Свойства товара
  .panel-body
    .row
      .col-sm-6
        =render 'admin/products/properties'


=render 'admin/products/groups'

app/views/admin/products/_groups.slim
.panel.panel-success
  .panel-heading.clearfix
    h3.panel-title.pull-left Связанные группы товаров
  .panel-body
    div ng-repeat="sub_product in obj.sub_products"
      .row.form-group
        .col-md-11
          input.form-control type="text" ng-model="sub_product.name" ng-blur="updateSubProduct(sub_product)"
        .col-md-1
          span.btn.btn-danger ng-click="destroySubProduct(sub_product)"
            i.fa.fa-lg.fa-trash
      .form-grop
        photos-uploaded resource-name="sub_product" resource-id="{{sub_product.id}}" show-form="true"
        uploader-component upload-url="/admin/sub_product/photos/upload" resource-name="sub_product_id" resource-id="{{sub_product.id}}"
        br


    span.btn.btn-success ng-click="setSubProduct(obj.product.id)"
      i.fa.fa-plus
      | Добавить группу

app/views/admin/products/_properties.erb
<div class="row">
  <div class="col-sm-12">
    <h4><strong>Свойства товара</strong></h4>
    <div ng-repeat="property in properties" class="property">
      <h4>
        <span ng-bind="property.name"></span>
        <span class="btn btn-success btn-xs add-property"><span class="fa fa-plus"></span></span>
      </h4>
      <div class="row property_add" style="display: none">
        <div class="col-xs-8">
          <input type="text" class="form-control"
                 ng-model="property.name"
          >
        </div>
        <div class="col-xs-4">
          <span class="btn btn-success"
          ><span class="fa fa-plus"></span></span>
        </div>
      </div>
      <div class="checkbox" ng-repeat="value in property.values">
        <label>
          <input type="checkbox"
                 ng-model="property[$index]"
                 ng-change="setPropertyValue(obj.product.id, property.id, value.id)"
                 ng-checked="value.checked"
          >
          <span ng-bind="value.value"></span>
        </label>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/edit.slim
form ng-init="obj.authenticity_token = '#{form_authenticity_token}'" ng-controller="ProductsFormCtrl"
  .page-header
    h2 Редактирование товара
    .page-header-actions
      button.btn.btn-success type="submit" ng-click="update(#{@product.id})" ng-init="findProduct(#{@product.id})"
        i class="fa fa-floppy-o"
        | Сохранить
      | &nbsp;
      =link_to "Отменить", admin_products_path, :class => "btn btn-default"
  /= link_to new_admin_product_path, class: 'btn btn-success' do
  /  i class="fa fa-plus"
  /  ' Добавить товар
  /
  =render 'admin/products/form'

app/views/admin/products/index.slim
.page-header
  h2 Список товаров
  .page-header-actions
    = link_to new_admin_product_path, class: 'btn btn-success' do
      i class="fa fa-plus"
      ' Добавить товар

.content
  table class="table table-bordered"
    thead
      tr
        th id
        th Название
        th Цена (руб.)
        th Фото
        th Бренд
        th Категория
        th Новинка
        th Действия

    tbody
      -@products.each do |item|
        tr
          td=item.id
          td=item.name
          td=item.price
          td
            -if item.photos.length > 0
              .thumbnail style="width: 100px"
                =image_tag item.photos.first.photo.thumb

          td
            -if item.brands
              ul
                -item.brands.each do |brand|
                  li=brand.name
          td
            ul
              -item.categories.each do |category|
                li=category.name
          td=item.new
          td
            = link_to edit_admin_product_path(item), class: 'btn btn-success' do
              span.fa.fa-lg.fa-edit
            br
            br
            = link_to admin_product_path(item), class: 'btn btn-danger', method: "delete" do
              span.fa.fa-lg.fa-trash
              
              
              